# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tnguye22/Simuscale_Samuel/simuscale

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tnguye22/Simuscale_Samuel/simuscale

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/tnguye22/Simuscale_Samuel/simuscale/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tnguye22/Simuscale_Samuel/simuscale/CMakeFiles /home/tnguye22/Simuscale_Samuel/simuscale//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tnguye22/Simuscale_Samuel/simuscale/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named simuscale

# Build rule for target.
simuscale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simuscale
.PHONY : simuscale

# fast build rule for target.
simuscale/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/simuscale.dir/build.make src/CMakeFiles/simuscale.dir/build
.PHONY : simuscale/fast

#=============================================================================
# Target rules for targets named simuscale-core

# Build rule for target.
simuscale-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simuscale-core
.PHONY : simuscale-core

# fast build rule for target.
simuscale-core/fast:
	$(MAKE) $(MAKESILENT) -f src/simuscale-core/CMakeFiles/simuscale-core.dir/build.make src/simuscale-core/CMakeFiles/simuscale-core.dir/build
.PHONY : simuscale-core/fast

#=============================================================================
# Target rules for targets named generated_headers

# Build rule for target.
generated_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generated_headers
.PHONY : generated_headers

# fast build rule for target.
generated_headers/fast:
	$(MAKE) $(MAKESILENT) -f src/simuscale-core/CMakeFiles/generated_headers.dir/build.make src/simuscale-core/CMakeFiles/generated_headers.dir/build
.PHONY : generated_headers/fast

#=============================================================================
# Target rules for targets named run_test_param_loader

# Build rule for target.
run_test_param_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_test_param_loader
.PHONY : run_test_param_loader

# fast build rule for target.
run_test_param_loader/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/run_test_param_loader.dir/build.make src/tests/CMakeFiles/run_test_param_loader.dir/build
.PHONY : run_test_param_loader/fast

#=============================================================================
# Target rules for targets named Cell_SyncClock_test

# Build rule for target.
Cell_SyncClock_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cell_SyncClock_test
.PHONY : Cell_SyncClock_test

# fast build rule for target.
Cell_SyncClock_test/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/Cell_SyncClock_test.dir/build.make src/tests/CMakeFiles/Cell_SyncClock_test.dir/build
.PHONY : Cell_SyncClock_test/fast

#=============================================================================
# Target rules for targets named run_Cell_SyncClock_test

# Build rule for target.
run_Cell_SyncClock_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_Cell_SyncClock_test
.PHONY : run_Cell_SyncClock_test

# fast build rule for target.
run_Cell_SyncClock_test/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/run_Cell_SyncClock_test.dir/build.make src/tests/CMakeFiles/run_Cell_SyncClock_test.dir/build
.PHONY : run_Cell_SyncClock_test/fast

#=============================================================================
# Target rules for targets named test_Cell

# Build rule for target.
test_Cell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Cell
.PHONY : test_Cell

# fast build rule for target.
test_Cell/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test_Cell.dir/build.make src/tests/CMakeFiles/test_Cell.dir/build
.PHONY : test_Cell/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/check.dir/build.make src/tests/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named utest

# Build rule for target.
utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utest
.PHONY : utest

# fast build rule for target.
utest/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/utest.dir/build.make src/tests/CMakeFiles/utest.dir/build
.PHONY : utest/fast

#=============================================================================
# Target rules for targets named itest

# Build rule for target.
itest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 itest
.PHONY : itest

# fast build rule for target.
itest/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/itest.dir/build.make src/tests/CMakeFiles/itest.dir/build
.PHONY : itest/fast

#=============================================================================
# Target rules for targets named test_param_loader

# Build rule for target.
test_param_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_param_loader
.PHONY : test_param_loader

# fast build rule for target.
test_param_loader/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test_param_loader.dir/build.make src/tests/CMakeFiles/test_param_loader.dir/build
.PHONY : test_param_loader/fast

#=============================================================================
# Target rules for targets named run_test_Cell

# Build rule for target.
run_test_Cell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_test_Cell
.PHONY : run_test_Cell

# fast build rule for target.
run_test_Cell/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/run_test_Cell.dir/build.make src/tests/CMakeFiles/run_test_Cell.dir/build
.PHONY : run_test_Cell/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/gtest-1.7.0/CMakeFiles/gtest_main.dir/build.make src/tests/gtest-1.7.0/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/gtest-1.7.0/CMakeFiles/gtest.dir/build.make src/tests/gtest-1.7.0/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... dist"
	@echo "... generated_headers"
	@echo "... itest"
	@echo "... run_Cell_SyncClock_test"
	@echo "... run_test_Cell"
	@echo "... run_test_param_loader"
	@echo "... uninstall"
	@echo "... utest"
	@echo "... Cell_SyncClock_test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... simuscale"
	@echo "... simuscale-core"
	@echo "... test_Cell"
	@echo "... test_param_loader"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

